Exercise 1 - NumPy array Indexing/Slicing

1.1) In this exercise, we will use the iris dataset. Load the "iris.csv" using the appropriate method for this file type (use the new functions from the package).

In [1]:
from si.io.csv_file import read_csv

data = read_csv('../datasets/iris/iris.csv', sep=',', features=True, label=True)
data.X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [2]:
data.y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

1.2) Select the penultimate independent variable.
What is the dimension of the resulting array?

In [ ]:
p_var = data.X[:,-2]
dim = p_var.shape
print(dim, p_var)

(150,) [1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 1.5 1.6 1.4 1.1 1.2 1.5 1.3 1.4
 1.7 1.5 1.7 1.5 1.  1.7 1.9 1.6 1.6 1.5 1.4 1.6 1.6 1.5 1.5 1.4 1.5 1.2
 1.3 1.5 1.3 1.5 1.3 1.3 1.3 1.6 1.9 1.4 1.6 1.4 1.5 1.4 4.7 4.5 4.9 4.
 4.6 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 4.4 4.5 4.1 4.5 3.9 4.8 4.
 4.9 4.7 4.3 4.4 4.8 5.  4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.
 4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3 3.  4.1 6.  5.1 5.9 5.6 5.8 6.6 4.5 6.3
 5.8 6.1 5.1 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9 6.7 4.9 5.7 6.
 4.8 4.9 5.6 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9
 5.7 5.2 5.  5.2 5.4 5.1]


1.3) Select the last 10 samples from the iris dataset.
What is the mean of the last 10 samples for each independent variable/feature?

In [4]:
last_10 = data.X[-10:]
mean_10 = last_10.mean(axis=0)
print(mean_10)

[6.45 3.03 5.33 2.17]


1.4) Select all samples from the dataset with values less than or equal to 6 for all independent variables/features.
How many samples do you obtain?

In [ ]:
mask = (data.X <= 6).all(axis=1)
filtered = data.X[mask]
print(filtered.shape)

(89, 4)


1.5) Select all samples with a class/label different from 'Iris-setosa'. 
How many samples do you obtain?

In [6]:
mask = data.y != 'Iris-setosa'
filtered_data = data.X[mask]
print(filtered_data.shape)

(100, 4)


Exercise 2 -  NumPy array Indexing/Slicing

2.a) General Examples

In [ ]:
import numpy as np
from si.data.dataset import Dataset

X = np.array([
    [1.0, 2.0, np.nan],
    [4.0, np.nan, 6.0],
    [7.0, 8.0, 9.0]
])
y = np.array([0, 1, 1])
features = np.array(['f1', 'f2', 'f3'])
label = "class"

dataset = Dataset(X, y, features, label)

print("\nOriginal dataset:")
print(dataset.X)

#dropna example
dataset_drop = Dataset(X.copy(), y.copy(), features, label).dropna()
print("\nAfter dropna():")
print(dataset_drop.X)

#fillna example
dataset_fill = Dataset(X.copy(), y.copy(), features, label).fillna("mean")
print("\nAfter fillna('mean'):")
print(dataset_fill.X)

#remove_by_index example
dataset_remove = Dataset(X.copy(), y.copy(), features, label).remove_by_index(1)
print("\nAfter remove_by_index(1):")
print(dataset_remove.X)



Original dataset:
[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]

After dropna():
[[7. 8. 9.]]

After fillna('mean'):
[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]

After remove_by_index(1):
[[ 1.  2. nan]
 [ 7.  8.  9.]]


2.b) Iris Dataset Examples:

In [ ]:
import numpy as np
from si.data.dataset import Dataset
from si.io.csv_file import read_csv

iris = read_csv("../datasets/iris/iris.csv", label="class")

print("Original Iris dataset shape:", iris.shape())

#dropna example

iris_drop_example = Dataset(iris.X.copy(), iris.y.copy(), iris.features, iris.label)
iris_drop_example.X[0, 1] = np.nan 
iris_drop_example.X[10, 2] = np.nan

print("\nBefore dropna — samples:", iris_drop_example.shape()[0])
iris_drop_example.dropna()
print("After dropna — samples:", iris_drop_example.shape()[0])

#fillna example

iris_fill_example = Dataset(iris.X.copy(), iris.y.copy(), iris.features, iris.label)
iris_fill_example.X[5, 0] = np.nan
iris_fill_example.X[15, 3] = np.nan

print("\nBefore fillna — NaN count:", np.isnan(iris_fill_example.X).sum())
iris_fill_example.fillna("mean")
print("After fillna — NaN count:", np.isnan(iris_fill_example.X).sum())

#remove_by_index example

iris_remove_example = Dataset(iris.X.copy(), iris.y.copy(), iris.features, iris.label)
print("\nBefore remove_by_index — samples:", iris_remove_example.shape()[0])
iris_remove_example.remove_by_index(0) 
print("After remove_by_index — samples:", iris_remove_example.shape()[0])


Original Iris dataset shape: (150, 4)

Before dropna — samples: 150
After dropna — samples: 148

Before fillna — NaN count: 2
After fillna — NaN count: 0

Before remove_by_index — samples: 150
After remove_by_index — samples: 149


Exercise 3 - Select Percentile 

3.3) Test the SelectPercentile class in a Jupyter notebook using the "iris.csv" dataset(classification).

In [ ]:
from si.io.csv_file import read_csv
from si.data.dataset import Dataset
from si.feature_selection.select_percentile import SelectPercentile 

data = read_csv('../datasets/iris/iris.csv', sep=',', features=True, label=True)
dataset = Dataset(data.X, data.y, features=data.features, label=data.label)

selector = SelectPercentile(percentile=0.5)

transformed_dataset = selector.fit_transform(dataset)

print("Transformed dataset shape:", transformed_dataset.X.shape)
print("Selected features:", transformed_dataset.features)

Transformed dataset shape: (150, 2)
Selected features: ['petal_length', 'petal_width']


Exercise 4 - Tanimoto

4.1) Test tanimoto similarity in a jupyter notebook

In [ ]:
from si.statistics.tanimoto_similarity import tanimoto_similarity

x = [True, False, True, True]
y = [
    [True, True, False, False],
    [False, False, True, True],
    [True, False, True, False]
]

similarities = tanimoto_similarity(x, y)
print(similarities)


[0.25       0.66666667 0.66666667]


Exercise 5 - PCA Class

5.2) Test the PCA class in a jupyter notebook using the iris.csv dataset (classificação).

In [ ]:
from si.io.csv_file import read_csv
from si.data.dataset import Dataset
from si.decomposition.pca import PCA

data = read_csv('../datasets/iris/iris.csv', sep=',', features=True, label=True)
dataset = Dataset(data.X, data.y, features=data.features, label=data.label)

pca = PCA(n_components=2)
transformed_dataset = pca.fit_transform(dataset)

print("Explained variance:", pca.explained_variance)

print(transformed_dataset.X)

Explained variance: [0.92461621 0.05301557]
[[-2.68420713 -0.32660731]
 [-2.71539062  0.16955685]
 [-2.88981954  0.13734561]
 [-2.7464372   0.31112432]
 [-2.72859298 -0.33392456]
 [-2.27989736 -0.74778271]
 [-2.82089068  0.08210451]
 [-2.62648199 -0.17040535]
 [-2.88795857  0.57079803]
 [-2.67384469  0.1066917 ]
 [-2.50652679 -0.65193501]
 [-2.61314272 -0.02152063]
 [-2.78743398  0.22774019]
 [-3.22520045  0.50327991]
 [-2.64354322 -1.1861949 ]
 [-2.38386932 -1.34475434]
 [-2.6225262  -0.81808967]
 [-2.64832273 -0.31913667]
 [-2.19907796 -0.87924409]
 [-2.58734619 -0.52047364]
 [-2.3105317  -0.39786782]
 [-2.54323491 -0.44003175]
 [-3.21585769 -0.14161557]
 [-2.30312854 -0.10552268]
 [-2.35617109  0.03120959]
 [-2.50791723  0.13905634]
 [-2.469056   -0.13788731]
 [-2.56239095 -0.37468456]
 [-2.63982127 -0.31929007]
 [-2.63284791  0.19007583]
 [-2.58846205  0.19739308]
 [-2.41007734 -0.41808001]
 [-2.64763667 -0.81998263]
 [-2.59715948 -1.10002193]
 [-2.67384469  0.1066917 ]
 [-2.866999

Exercise 6 - Stratified splitting

6.2) Test the "stratified_train_test_split" function with the iris dataset.

In [ ]:
from si.io.csv_file import read_csv
from si.data.dataset import Dataset
from si.model_selection.split import stratified_train_test_split
import numpy as np

data = read_csv('../datasets/iris/iris.csv', sep=',', features=True, label=True)
dataset = Dataset(data.X, data.y, features=data.features, label=data.label)

train_data, test_data = stratified_train_test_split(dataset, test_size=0.2, random_state=42)

print("Train class distribution:", np.unique(train_data.y, return_counts=True))
print("Test class distribution:", np.unique(test_data.y, return_counts=True))


Train class distribution: (array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object), array([40, 40, 40]))
Test class distribution: (array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object), array([10, 10, 10]))


Exercise 7 - KNNRegressor with RMSE

7.3) Test the "KNNRegressor" class using the "cpu.csv" dataset (regression).

In [ ]:
from si.io.csv_file import read_csv
from si.data.dataset import Dataset
from si.models.knn_regressor import KNNRegressor
from si.metrics.rmse import rmse
from si.model_selection.split import train_test_split

data = read_csv('../datasets/cpu/cpu.csv', sep=',', features=True, label=True)
dataset = Dataset(data.X, data.y, features=data.features, label=data.label)

train_data, test_data = train_test_split(dataset, test_size=0.2, random_state=42)

knn = KNNRegressor(k=5)
knn.fit(train_data)

y_pred = knn.predict(test_data.X)

rmse_score = rmse(test_data.y, y_pred)
print(f"RMSE: {rmse_score:.1f}")


RMSE: 105.0


Exercise 8 - RidgeRegression with Least Squares

8.1) Test the "RidgeRegressionLeastSquares" class using the "cpu.csv" dataset.

In [ ]:
from si.io.csv_file import read_csv
from si.data.dataset import Dataset
from si.models.ridge_regression_least_squares import RidgeRegressionLeastSquares
from si.model_selection.split import train_test_split

data = read_csv('../datasets/cpu/cpu.csv', sep=',', features=True, label=True)
dataset = Dataset(data.X, data.y, features=data.features, label=data.label)

train_data, test_data = train_test_split(dataset, test_size=0.2, random_state=42)

ridge = RidgeRegressionLeastSquares(l2_penalty=1.0, scale=True)
ridge.fit(train_data)

y_pred = ridge.predict(test_data.X)
mse_score = ridge.score(test_data)
print(f"MSE: {mse_score:.1f}")


MSE: 5806.1


Exercise 9 - RandomForestClassifier class

9.2) Test the random forest class using the following protocol:
1.Use the iris.csv dataset
2.Split the data into train and test sets
3.Create the RandomForestClassifier model
4.Train the model. What is the score of the model on the test set?

In [ ]:
from si.io.csv_file import read_csv
from si.model_selection.split import train_test_split
from si.models.random_forest_classifier import RandomForestClassifier

data = read_csv('../datasets/iris/iris.csv', sep=',', features=True, label=True)

train, test = train_test_split(data, test_size=0.2, random_state=42)

rf = RandomForestClassifier(n_estimators=20, max_depth=5)

rf.fit(train)
score = rf.score(test)
print("Test accuracy:", score)


Test accuracy: 0.9666666666666667
