Exercise 1 - NumPy array Indexing/Slicing

1.1) In this exercise, we will use the iris dataset. Load the "iris.csv" using the appropriate method for this file type (use the new functions from the package).

In [2]:
from si.io.csv_file import read_csv

data = read_csv('../datasets/iris/iris.csv', sep=',', features=True, label=True)
data.X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [3]:
data.y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

1.2) Select the penultimate independent variable.
What is the dimension of the resulting array?

In [4]:
# select the penultimate row
p_var = data.X[:,-2]
# uses shape to get the dimensions of the array
dim = p_var.shape
print(dim, p_var)

(150,) [1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 1.5 1.6 1.4 1.1 1.2 1.5 1.3 1.4
 1.7 1.5 1.7 1.5 1.  1.7 1.9 1.6 1.6 1.5 1.4 1.6 1.6 1.5 1.5 1.4 1.5 1.2
 1.3 1.5 1.3 1.5 1.3 1.3 1.3 1.6 1.9 1.4 1.6 1.4 1.5 1.4 4.7 4.5 4.9 4.
 4.6 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 4.4 4.5 4.1 4.5 3.9 4.8 4.
 4.9 4.7 4.3 4.4 4.8 5.  4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.
 4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3 3.  4.1 6.  5.1 5.9 5.6 5.8 6.6 4.5 6.3
 5.8 6.1 5.1 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9 6.7 4.9 5.7 6.
 4.8 4.9 5.6 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9
 5.7 5.2 5.  5.2 5.4 5.1]


1.3) Select the last 10 samples from the iris dataset.
What is the mean of the last 10 samples for each independent variable/feature?

In [5]:
last_10 = data.X[-10:]
mean_10 = last_10.mean(axis=0)
print(mean_10)

[6.45 3.03 5.33 2.17]


1.4) Select all samples from the dataset with values less than or equal to 6 for all independent variables/features.
How many samples do you obtain?

In [6]:
# mask for values less than or equal to 6
mask = (data.X <= 6).all(axis=1)
filtered = data.X[mask]
print(filtered.shape)

(89, 4)


1.5) Select all samples with a class/label different from 'Iris-setosa'. 
How many samples do you obtain?

In [7]:
mask = data.y != 'Iris-setosa'
filtered_data = data.X[mask]
print(filtered_data.shape)

(100, 4)


Examples of how to use these methods:

3.3) Test the SelectPercentile class in a Jupyter notebook using the "iris.csv" dataset(classification).

In [8]:
from si.io.csv_file import read_csv
from si.data.dataset import Dataset
# Ensure this line reloads the new code
from si.feature_selection.select_percentile import SelectPercentile 

# Load the iris dataset
data = read_csv('../datasets/iris/iris.csv', sep=',', features=True, label=True)
dataset = Dataset(data.X, data.y, features=data.features, label=data.label)

# Initialize SelectPercentile with a percentile of 50%
# The default score_func (f_classification) is used here.
selector = SelectPercentile(percentile=0.5)

# Fit and transform the dataset
transformed_dataset = selector.fit_transform(dataset) # This should now work

# Print the transformed dataset shape and selected features
print("Transformed dataset shape:", transformed_dataset.X.shape)
print("Selected features:", transformed_dataset.features)

Transformed dataset shape: (150, 2)
Selected features: ['petal_length', 'petal_width']


4.1) Test tanimoto similarity in a jupyter notebook

In [9]:
from si.statistics.tanimoto_similarity import tanimoto_similarity

x = [True, False, True, True]
y = [
    [True, True, False, False],
    [False, False, True, True],
    [True, False, True, False]
]

similarities = tanimoto_similarity(x, y)
print(similarities)  # Output: [0.25, 0.6, 0.666...]


[0.25 0.25 0.25]


5.2) Test the PCA class in a jupyter notebook using the iris.csv dataset (classificação).

In [10]:
from si.io.csv_file import read_csv
from si.data.dataset import Dataset
from si.decomposition.pca import PCA

# Load the iris dataset
data = read_csv('../datasets/iris/iris.csv', sep=',', features=True, label=True)
dataset = Dataset(data.X, data.y, features=data.features, label=data.label)

# Fit and transform using PCA
pca = PCA(n_components=2)
transformed_dataset = pca.fit_transform(dataset)

# Print the explained variance
print("Explained variance:", pca.explained_variance)

# Print the transformed data
print(transformed_dataset.X)

Explained variance: [0.92461621 0.05301557]
[[-2.68420713 -0.32660731]
 [-2.71539062  0.16955685]
 [-2.88981954  0.13734561]
 [-2.7464372   0.31112432]
 [-2.72859298 -0.33392456]
 [-2.27989736 -0.74778271]
 [-2.82089068  0.08210451]
 [-2.62648199 -0.17040535]
 [-2.88795857  0.57079803]
 [-2.67384469  0.1066917 ]
 [-2.50652679 -0.65193501]
 [-2.61314272 -0.02152063]
 [-2.78743398  0.22774019]
 [-3.22520045  0.50327991]
 [-2.64354322 -1.1861949 ]
 [-2.38386932 -1.34475434]
 [-2.6225262  -0.81808967]
 [-2.64832273 -0.31913667]
 [-2.19907796 -0.87924409]
 [-2.58734619 -0.52047364]
 [-2.3105317  -0.39786782]
 [-2.54323491 -0.44003175]
 [-3.21585769 -0.14161557]
 [-2.30312854 -0.10552268]
 [-2.35617109  0.03120959]
 [-2.50791723  0.13905634]
 [-2.469056   -0.13788731]
 [-2.56239095 -0.37468456]
 [-2.63982127 -0.31929007]
 [-2.63284791  0.19007583]
 [-2.58846205  0.19739308]
 [-2.41007734 -0.41808001]
 [-2.64763667 -0.81998263]
 [-2.59715948 -1.10002193]
 [-2.67384469  0.1066917 ]
 [-2.866999

6.2) Test the "stratified_train_test_split" function with the iris dataset.

In [11]:
from si.io.csv_file import read_csv
from si.data.dataset import Dataset
from si.model_selection.split import stratified_train_test_split
import numpy as np

# Load the iris dataset
data = read_csv('../datasets/iris/iris.csv', sep=',', features=True, label=True)
dataset = Dataset(data.X, data.y, features=data.features, label=data.label)

# Perform stratified train-test split
train_data, test_data = stratified_train_test_split(dataset, test_size=0.2, random_state=42)

# Print the class distribution in train and test sets
print("Train class distribution:", np.unique(train_data.y, return_counts=True))
print("Test class distribution:", np.unique(test_data.y, return_counts=True))


Train class distribution: (array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object), array([40, 40, 40]))
Test class distribution: (array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object), array([10, 10, 10]))


7.3) Test the "KNNRegressor" class using the "cpu.csv" dataset (regression).

In [15]:
from si.io.csv_file import read_csv
from si.data.dataset import Dataset
from si.models.knn_regressor import KNNRegressor
from si.metrics.rmse import rmse
from si.model_selection.split import train_test_split

# Load the CPU dataset
data = read_csv('../datasets/cpu/cpu.csv', sep=',', features=True, label=True)
dataset = Dataset(data.X, data.y, features=data.features, label=data.label)

# Split the dataset into training and testing sets
train_data, test_data = train_test_split(dataset, test_size=0.2, random_state=42)

# Initialize and fit the KNNRegressor
knn = KNNRegressor(k=5)
knn.fit(train_data)

# Predict on the test set
y_pred = knn.predict(test_data.X)

# Compute RMSE
rmse_score = rmse(test_data.y, y_pred)
print(f"RMSE: {rmse_score:.1f}")


RMSE: 105.0


8.1) Test the "RidgeRegressionLeastSquares" class using the "cpu.csv" dataset.

In [14]:
from si.io.csv_file import read_csv
from si.data.dataset import Dataset
from si.models.ridge_regression_least_squares import RidgeRegressionLeastSquares
from si.model_selection.split import train_test_split

# Load your dataset
data = read_csv('../datasets/cpu/cpu.csv', sep=',', features=True, label=True)
dataset = Dataset(data.X, data.y, features=data.features, label=data.label)

# Split the dataset
train_data, test_data = train_test_split(dataset, test_size=0.2, random_state=42)

# Initialize and fit the model
ridge = RidgeRegressionLeastSquares(l2_penalty=1.0, scale=True)
ridge.fit(train_data)

# Predict and score
y_pred = ridge.predict(test_data.X)
mse_score = ridge.score(test_data)
print(f"MSE: {mse_score:.1f}")


MSE: 5806.1


9.2) Test the random forest class using the following protocol:
1.Use the iris.csv dataset
2.Split the data into train and test sets
3.Create the RandomForestClassifier model
4.Train the model. What is the score of the model on the test set?

In [17]:
from si.io.csv_file import read_csv
from si.data.dataset import Dataset
from si.models.random_forest_classifier import RandomForestClassifier
from si.model_selection.split import train_test_split

# Load the iris dataset
data = read_csv('../datasets/iris/iris.csv', sep=',', features=True, label=True)
dataset = Dataset(data.X, data.y, features=data.features, label=data.label)

# Split the dataset into training and testing sets
train_data, test_data = train_test_split(dataset, test_size=0.2, random_state=42)

# Initialize and fit the RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, max_features=None, min_sample_split=2, max_depth=None, mode='gini', seed=42)
rf.fit(train_data)

# Score the model on the test set
score = rf.score(test_data)
print(f"Test set accuracy: {score:.4f}")


TypeError: '<=' not supported between instances of 'int' and 'NoneType'